onboardingtasks/invitationapp/urls.py
from django.urls import path
from . import views


app_name = 'invitationapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name='login'),
    path('signup/', views.singup, name='signup'),
    path('logout/', views.logout, name='logout'),
]

onboardingtasks/onboardingtasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('pages/', include('pagesapp.urls')),
    path('bookmarks/', include('bookmarksapp.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('django.contrib.auth.urls')),
    url(r'^places/', include('placesapp.urls')),
    path('events/', include('eventsapp.urls')),
]

onboardingtasks/pagesapp/urls.py
from django.urls import path
from django.conf.urls import url
from .views import HomePageView, NavPageView

app_name = "pagesapp"

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    url(r'^', NavPageView.as_view(), name="navpage")
]

onboardingtasks/invitationapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Invitations


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class InvitationForm(forms.ModelForm):
    class Meta:
        model = Invitations
        fields = ['invitee_email', ]

onboardingtasks/invitationapp/templates/invitationapp/base.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel ="stylesheet" type="text/css" href="{% static 'invitationapp/css.css' %}"/>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/">All Apps</a>
                <a class="navbar-brand" href="{% url 'invitationapp:index' %}">Invitations</a>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    </ul>
                    {% if user.is_authenticated%}
                        <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'invitationapp:logout' %}">Logout</a>
                    {% else %}
                        <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'invitationapp:signup' %}">Signup</a>
                        <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'invitationapp:login' %}">Login</a>
                    {% endif %}
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-8">
                    {% block container %}

                    {% endblock %}
                </div>
            </div>
        </div>
        {% block content %}

        {% endblock %}
    </body>
</html>

onboardingtasks/invitationapp/templates/invitationapp/index.html
{% extends "invitationapp/base.html"%}
{% load crispy_forms_tags %}
{% block container%}
    <table class="table table-bordered">
        <tr>
            <th>Invitee</th>
            <th>Status</th>
        </tr>
        {% for invitee in invite_list %}
            <tr>
                <td>{{ invitee.invitee_email }}</td>
                {% if invitee.registered %}
                    <td>Registered</td>
                {% else %}
                    <td>Not Registered</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block content%}
    <form class = "form-inline" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Invite" class="btn btn-primary"/>
    </form>
{% endblock %}

onboardingtasks/invitationapp/templates/invitationapp/invalidlogin.html
{% extends "bookmarksapp/base.html"%}
{% block content%}
    <h1> Sorry, Invalid Credentials entered...</h1>
    <a href="{% url 'bookmarksapp:login'%}">
        <h2> Try to login with correct credentials</h2>
    </a>
{% endblock %}

onboardingtasks/invitationapp/templates/invitationapp/login.html
{% extends "invitationapp/base.html"%}
{% block container%}
    <h1 class="mt-2">Login</h1>
    <hr class="mt-0 mb-4">
    <form method="POST">
        {% csrf_token %}
        <p class="form-inline" ><label for="id_username">Username:</label> <input type="text" class="form-control" name="username" autofocus required id="id_username"></p>
        <p class="form-inline" ><label for="id_password">Password:</label> <input type="password" class="form-control" name="password" required id="id_password"></p>
        <button class="btn btn-primary"  type="submit">Login</button>
    </form>
    <form action="{% url 'invitationapp:signup' %}">
        <p>Not Yet Created Account.. Go to below signup Page.</p>
        <input class="btn btn-primary"  type="submit" value="Signup" />
    </form>
{% endblock%}

onboardingtasks/invitationapp/templates/invitationapp/signup.html
{% extends "invitationapp/base.html"%}
{% load crispy_forms_tags %}
{% block container%}
    <h1 class="mt-2">Signup</h1>
    <hr class="mt-0 mb-4">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy}}
        <button class="btn btn-success" type="submit">Sign up</button>
    </form>
    <form action="{% url 'invitationapp:login'%}">
        <p>Already had an account. Please Login here.</p>
        <input class="btn btn-success" type="submit" value="Sign in" />
    </form>
{% endblock %}