onboardingtasks/authenticationapp/urls.py
from django.urls import path
from . import views

app_name = "authenticationapp"
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout")
]

onboardingtasks/onboardingtasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('pages/', include('pagesapp.urls')),
    path('bookmarks/', include('bookmarksapp.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('django.contrib.auth.urls')),
    url(r'^places/', include('placesapp.urls')),
    path('events/', include('eventsapp.urls')),
]

onboardingtasks/pagesapp/urls.py
from django.urls import path
from django.conf.urls import url
from .views import HomePageView, NavPageView

app_name = "pagesapp"

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    url(r'^', NavPageView.as_view(), name="navpage")
]

onboardingtasks/useraccountsapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create', views.CreateUserAccounts.as_view(), name="create"),
]

onboardingtasks/useraccountsapp/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

# Create your models here.


class UserAccounts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile_info')
    profile_picture = models.ImageField(upload_to='./accounts_meida', blank=True)
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='')
    date_of_birth = models.DateField()
    phone_number = PhoneNumberField(null=False, blank=False, unique=True)

    def __str__(self):
        return self.user

onboardingtasks/useraccountsapp/forms.py
from django import forms
from .models import UserAccounts


class CreateUserAccountsForm(forms.ModelForm):
    class Meta:
        model = UserAccounts
        fields = '__all__'
        widgets = {
            'gender': forms.RadioSelect(),
            'date_of_birth': forms.DateInput(attrs={'placeholder': 'DD-MM-YYYY', 'format': '%d-%m-%Y'})
        }

onboardingtasks/useraccountsapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .models import UserAccounts
from .forms import CreateUserAccountsForm
# Create your views here.


class CreateUserAccounts(CreateView):
    model = UserAccounts
    form_class = CreateUserAccountsForm
    template_name = "useraccountsapp/usercreationform.html"

    def form_valid(self, form):
        print('saving..')
        form.user = self.request.user
        self.object = form.save()
        return super(CreateUserAccounts, self).form_valid(form)

onboardingtasks/useraccountsapp/templates/useraccountsapp/base.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    </ul>
                      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'authenticationapp:signup' %}">Signup</a>
                      <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'authenticationapp:login' %}">Login</a>
                  </div>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-8">
              {% block container %}
              {% endblock %}
            </div>
          </div>
        </div>
    </body>
</html>

onboardingtasks/useraccountsapp/templates/useraccountsapp/usercreationform.html
{% extends 'useraccountsapp/base.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="row">
          <div class="col-4">
            {{ form.first_name|as_crispy_field }}
          </div>
          <div class="col-4">
            {{ form.middle_name|as_crispy_field }}
          </div>
            <div class="col-4">
            {{ form.last_name|as_crispy_field }}
          </div>
        </div>
        <p>{{form.gender.label}}<span class="asteriskField">*</span> </p>
        <div class="row">
            {% for g in form.gender %}
            <div class="col-2">
                <p>{{g}}</p>
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-4">
                {{ form.date_of_birth|as_crispy_field }}
            </div>
        </div>
        <div class="row">
          <div class="col-4">
            {{ form.phone_number|as_crispy_field }}
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            {{ form.profile_picture|as_crispy_field }}
          </div>
        </div>
        <div class="float-right">
            <input type="submit" value="Save" class="btn btn-primary">
        </div>

    </form>
{% endblock %}