onboardingtasks/eventsapp/urls.py
from django.urls import path
from . import views


app_name = "eventsapp"
urlpatterns = [
    path('', views.EventsListView.as_view(), name="list"),
    path('create', views.EventsCreateView.as_view(), name='create'),
]

onboardingtasks/onboardingtasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('pages/', include('pagesapp.urls')),
    path('bookmarks/', include('bookmarksapp.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('django.contrib.auth.urls')),
    url(r'^places/', include('placesapp.urls')),
    path('events/', include('eventsapp.urls')),
]

onboardingtasks/pagesapp/urls.py
from django.urls import path
from django.conf.urls import url
from .views import HomePageView, NavPageView

app_name = "pagesapp"

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    url(r'^', NavPageView.as_view(), name="navpage")
]

onboardingtasks/placesapp/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "placesapp"

urlpatterns = [
    path('', views.List_View.as_view(), name="list"),
    url(r'(?P<pk>\d+)$', views.Detail_View.as_view(), name="details"),
    path('<city>', views.List_View.as_view(), name="list"),
    url(r'create/$', views.Create_View.as_view(), name="create"),
]

onboardingtasks/eventsapp/models.py
from model_utils.models import TimeStampedModel
from placesapp.models import Places
from django.db import models
from taggit.managers import TaggableManager


class Events(TimeStampedModel):
    title = models.CharField(max_length=100)
    place = models.ForeignKey(Places, on_delete=models.CASCADE)
    tags = TaggableManager()
    created_by = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class EventTime(models.Model):
    event_start_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    event_end_time = models.DateTimeField(auto_now=False, auto_now_add=False)
    event = models.ForeignKey(Events, on_delete=models.CASCADE, related_name="event_times")

onboardingtasks/eventsapp/forms.py
from django.forms import ModelForm
from .models import Events, EventTime
from django.contrib.admin import widgets


class EventForm(ModelForm):
    class Meta:
        model = Events
        fields = "__all__"


class EventTimeForm(ModelForm):
    class Meta:
        model = EventTime
        exclude = ('event',)
        widgets = {'event_start_time': widgets.AdminSplitDateTime(), 'event_end_time': widgets.AdminSplitDateTime()}

onboardingtasks/eventsapp/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Events, EventTime
from .forms import EventForm, EventTimeForm
from datetime import datetime
# Create your views here.


class EventsListView(ListView):
    model = Events
    template_name = "eventsapp/list.html"

    def get(self, request):
        events = self.get_queryset(request)
        return render(request, self.template_name, {'events': events})

    def get_queryset(self, request):
        qs = super().get_queryset()
        results = set()
        if 'weekday' in request.GET:
            for q in qs:
                c_all = q.event_times.all()
                for c in c_all:
                    if str(c.event_start_time.weekday()) == (request.GET['weekday']):
                        results.add(q)
            return results
        elif'yyyy-mm' in request.GET:
            year, month = request.GET['yyyy-mm'].split('-')
            qs = set(qs.filter(event_times__event_start_time__year=year, event_times__event_start_time__month=month))
        elif 'yyyy-mm-dd' in request.GET:
            year, month, date = request.GET['yyyy-mm-dd'].split('-')
            qs = set(qs.filter(event_times__event_start_time__year=year, event_times__event_start_time__month=month, event_times__event_start_time__day=date))
        return qs


class EventsCreateView(CreateView):
    def get(self, request):
        eform = EventForm()
        tform = EventTimeForm()
        template_name = "eventsapp/createview.html"
        return render(request, template_name, {'eform': eform, 'tform': tform, })

    def post(self, request):
        template_name = "eventsapp/createview.html"
        eform = EventForm(request.POST)
        if eform.is_valid():
            eform.title = eform.cleaned_data['title']
            eform.place = eform.cleaned_data['place']
            eform.tags = eform.cleaned_data['tags']
            eform.created_by = eform.cleaned_data['created_by']
            e = eform.save()
        tform = EventTime()
        event_start_time = request.POST['event_start_time_0'] + " " + request.POST['event_start_time_1']
        event_start_time = datetime.strptime(event_start_time, '%Y-%m-%d %H:%M:%S')
        tform.event_start_time = event_start_time
        event_end_time = request.POST['event_end_time_0'] + " " + request.POST['event_end_time_1']
        event_end_time = datetime.strptime(event_end_time, '%Y-%m-%d %H:%M:%S')
        tform.event_end_time = event_end_time
        tform.event = Events.objects.get(pk=e.pk)
        tform.save()
        return render(request, template_name, {})

onboardingtasks/eventsapp/templates/eventsapp/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {{ tform.media }}
        {{ eform.media }}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'eventsapp/css.css' %}">
        {% block title%}

        {% endblock %}
        <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
        <script type="text/javascript" src="/admin/jsi18n/"></script>
        <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
        <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
        <script type="text/javascript" src="/static/admin/js/core.js"></script>
        <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
        <script type="text/javascript" src="/static/admin/js/actions.js"></script>
        <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
        <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
        <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
        <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
        <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'eventsapp:list'%}">Home</a>
            {% block navbarcontent%}

            {% endblock %}
        </nav>
        <div class="container">
            {% block homepagecontent %}

            {% endblock %}
        </div>
        {% block filters%}
        {% endblock %}
    </body>
</html>

onboardingtasks/eventsapp/templates/eventsapp/createview.html
{% extends "eventsapp/base.html" %}
{% block homepagecontent %}
    {{ tform.media }}
    <form id="Form1"  action = "{% url 'placesapp:create' %}"  method="GET"  style = "display:inline;">
        {% csrf_token %}
    </form>
    <form id="Form2"  action = "{% url 'eventsapp:create' %}"  method="POST"  style = "display:inline;">
        {% csrf_token %}
        {% for field in eform %}
            {% if field.label == "Place"%}
                <div style = "display:-webkit-box;">
                    <p>{{field.label}}:{{field}}</p>
                    <button class="btn btn-primary btn-sm" name="path" value="{{request.path}}" form="Form1">Add New Place </button>
                </div>
            {% else %}
                <p>{{field.label}}:{{field}}</p>
            {% endif %}
        {% endfor %}
        {{tform.as_p}}
        <input class="btn btn-primary" type="submit" value="Create"/>
    </form>
{% endblock %}

onboardingtasks/eventsapp/templates/eventsapp/filters.html
<div id="right-nav">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>Filters</h3>
                <div style = "display:-webkit-box;">
                    <form action = "{% url 'eventsapp:list'%}" method="GET">
                        By week day:
                        <select  name="weekday">
                            <option value="0">Monday</option>
                            <option value="1">Tuesday</option>
                            <option value="2">Wednesday</option>
                            <option value="3">Thursday</option>
                            <option value="4">Friday</option>
                            <option value="5">Saturday</option>
                            <option value="6">Sunday</option>
                        </select>
                        <button class="btn btn-primary btn-sm" type="submit">Submit</button>
                    </form>
                </div>
                <form action = "#" method="GET" class="form-inline" >
                    By Month:
                    <input type="month" class="form-control" name="yyyy-mm">
                    <button class="btn btn-primary btn-sm" type="submit">Submit</button>
                </form>
                <form class="form-inline">
                    By Specific date
                    <input type="date" name="yyyy-mm-dd" class="form-control">
                    <button class="btn btn-primary btn-sm" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

onboardingtasks/eventsapp/templates/eventsapp/list.html
{% extends 'eventsapp/base.html' %}
{% block homepagecontent %}
    {% for event in events %}
        <a href="{{event.id}}"><h2>{{event.title}}</h2></a>
    {% endfor %}
    <a href="{% url 'eventsapp:create'%}"><button class="btn btn-primary btn-m" >Create new event</button></a>
{% endblock %}

{% block filters%}
    {% include 'eventsapp/filters.html' %}
{% endblock %}