onboardingtasks/authenticationapp/urls.py
from django.urls import path
from . import views

app_name = "authenticationapp"
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name="logout")
]

onboardingtasks/onboardingtasks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('pages/', include('pagesapp.urls')),
    path('bookmarks/', include('bookmarksapp.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('django.contrib.auth.urls')),
    url(r'^places/', include('placesapp.urls')),
    path('events/', include('eventsapp.urls')),
]

onboardingtasks/pagesapp/urls.py
from django.urls import path
from django.conf.urls import url
from .views import HomePageView, NavPageView

app_name = "pagesapp"

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    url(r'^', NavPageView.as_view(), name="navpage")
]

onboardingtasks/authenticationapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

onboardingtasks/authenticationapp/views.py
from django.contrib.auth import authenticate, login as mylogin, logout as mylogout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .forms import UserCreationForm
from django.core.mail import send_mail
from invitationapp.models import Invitations

# Create your views here.


def index(request):
    if str(request.user) == 'AnonymousUser':
        return HttpResponseRedirect(reverse('authenticationapp:login'))
    else:
        return render(request, 'authenticationapp/index.html')


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('authenticationapp:index'))
    else:
        if request.method == 'GET':
            template = 'authenticationapp/login.html'
            return render(request, template)
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                mylogin(request, user)
                return HttpResponseRedirect(reverse('authenticationapp:index'))
            else:
                return render(request, "authenticationapp/invalidlogin.html")


def signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('authenticationapp:index'))
    else:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                data_from_table = form.save()
                invitor_exist = Invitations.objects.filter(invitee_email=data_from_table.email, registered='False')
                if invitor_exist:
                    for i in invitor_exist:
                        i.registered = 'True'
                        i.save()
                        print(str(i.invitee_email), str(i.invitor_email))
                        send_mail('Invitaion', str(i.invitee_email) + ' has accepted your invitation and registered',
                                  'pavan1995143.pavan@gmail.com', [str(i.invitor_email), ])

                username = form.cleaned_data.get('email')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(request, username=username, password=raw_password)
                mylogin(request, user)
                return HttpResponseRedirect(reverse('authenticationapp:index'))
        else:
            form = UserCreationForm()
        return render(request, 'authenticationapp/signup.html', {'form': form})


def logout(request):
    mylogout(request)
    return HttpResponseRedirect(reverse('authenticationapp:login'))

onboardingtasks/authenticationapp/templates/authenticationapp/index.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
        <div class="jumbotron">
          <h1 class="display-4"  style="text-align:center" >List of Apps </h1>
            <div class="float-right">
                <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'authenticationapp:logout' %}">Logout</a>
            </div>
        </div>
        <div class="container">
            <h3><a href="pages/" >Pages</a></h3>
            <h3><a href="bookmarks/" >Bookmarks</a></h3>
            <h3><a href="admin/" >Admin </a></h3>
            <h3><a href="places/" >Places </a></h3>
            <h3><a href="events/" >Events </a></h3>
            <h3><a href="invitations/" >Invitations </a></h3>
        </div>
    </body>

onboardingtasks/authenticationapp/templates/authenticationapp/invalidlogin.html
{% extends "authenticationapp/base.html"%}
{% block content%}
    <h1> Sorry, Invalid Credentials entered...</h1>
    <a href="{% url 'authenticationapp:login'%}">
    <h2> Try to login with correct credentials</h2>
    </a>
{% endblock %}

onboardingtasks/authenticationapp/templates/authenticationapp/login.html
{% extends "authenticationapp/base.html"%}
{% load crispy_forms_tags %}
{% block container%}
<h1 class="mt-2">Login</h1>
<hr class="mt-0 mb-4">
    <form action="{% url 'authenticationapp:signup' %}" id="form1">
    </form>
    <form action = "{% url 'authenticationapp:login' %}" method="POST">
    {% csrf_token %}
      <p class="form-inline" ><label for="id_username">Username:</label> <input type="text" class="form-control" name="username" autofocus required id="id_username"></p>
    <p class="form-inline" ><label for="id_password">Password:</label> <input class="form-control" type="password" name="password" required id="id_password"></p>
        <button class="btn btn-primary"  type="submit">Login</button>
        <input class="btn btn-primary"  type="submit" value="Signup" form="form1" />
    </form>
{% endblock%}

onboardingtasks/authenticationapp/templates/authenticationapp/signup.html
{% extends "authenticationapp/base.html"%}
{% load crispy_forms_tags %}
{% block container%}
<h1 class="mt-2">Signup</h1>
<hr class="mt-0 mb-4">
 <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Sign up</button>
  </form>
  <form action="{% url 'authenticationapp:login' %}">
    <p>Already had an account. Please Login here.</p>
    <input class="btn btn-success" type="submit" value="Sign in" />
</form>
{% endblock%}